services:
  whiteboardapi:
    container_name: WhiteBoardAPI
    build:
      context: ./WhiteBoardAPI
    ports:
      - "10000:10000"
    depends_on:
      - mongodb
        
  whiteboardview:
    container_name: WhiteBoardView
    build:
      context: ./WhiteBoardView
    ports:
      - "10001:10001"
    depends_on:
      - whiteboardapi
  
  mongodb:
    container_name: WhiteBoardMongo
    image: mongo
    ports:
      - "27017:27017"